# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Retrier < Formula
  desc "A tool for retrying commands until they succeed"
  homepage "https://github.com/dantheman0207/retrier"
  version "0.1.20"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/dantheman0207/homebrew-retrier/releases/download/v0.1.20/retrier_0.1.20_darwin_arm64.tar.gz"
    sha256 "74cd3b4626f31224e77fb319193e5d8231b3653ded863e76bd33fd805011968a"

    define_method(:install) do
      bin.install "retrier"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/retrier --version")
  end
end
