# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sysdash < Formula
  desc "Keyboard-driven macOS system dashboard"
  homepage "https://github.com/dantheman0207/sysdash"
  version "1.0.0"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/dantheman0207/sysdash/releases/download/v1.0.0/sysdash_1.0.0_darwin_arm64.tar.gz"
    sha256 "a01775589d2e3596f48170697d3018ce4ea52d12638a04fe8be2e73373d03fc6"

    define_method(:install) do
      bin.install "sysdash"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sysdash --version")
  end
end
