# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sysdash < Formula
  desc "Keyboard-driven macOS system dashboard"
  homepage "https://github.com/dantheman0207/sysdash"
  version "1.0.1"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/dantheman0207/sysdash/releases/download/v1.0.1/sysdash_1.0.1_darwin_arm64.tar.gz"
    sha256 "a702a031a665c00d9c890342dfa5e016bc3b064b33979c24180ab7f77447a622"

    define_method(:install) do
      bin.install "sysdash"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sysdash --version")
  end
end
