# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sysdash < Formula
  desc "Keyboard-driven macOS system dashboard"
  homepage "https://github.com/dantheman0207/sysdash"
  version "1.1.0"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/dantheman0207/sysdash/releases/download/v1.1.0/sysdash_1.1.0_darwin_arm64.tar.gz"
    sha256 "a8055de87fb2ff3738567b57269f8303236fe536b08a999dbc02e019e7ceef44"

    define_method(:install) do
      bin.install "sysdash"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sysdash --version")
  end
end
